#define DEVICE ""
#define WIFI_SSID ""
#define WIFI_PASSWORD ""
#define INFLUXDB_URL ""
#define INFLUXDB_TOKEN ""
#define INFLUXDB_ORG ""
#define INFLUXDB_BUCKET ""
#define TZ_INFO ""
#define NUMPIXELS 1
#define DATAPIN    33
#define CLOCKPIN   21
#define CLICKTHRESHHOLD 80